version: "3"

services:
  api:
    build: .
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 1515:1515

  redis:
    image: redis
    restart: always
    volumes:
      - ./data:/data